spring:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 3
        format_sql: true
        highlight_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/boardapi_db?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: rlatnehd@123

  redis:
    host: localhost
    port: 6378


#rsa:
#  private-key: classpath:certs/private.pem
#  public-key: classpath:certs/public.pem

jwt:
  secret_key: zckcriwtzydklapagkzaxplmrzcrhhzkqsbiwxnflwqmvevghnmpyotmdjgxwrxbanqjtsukiuhvlyccwisjthyxecidxrqtdjvpaoabuvrouyhzjoijdkojwczuldnvnbmrnwpzajwyvoiejxychvnglaezkvem

firebase:
  firebaseConfigPath: /firebase/board-api-e5a2c-firebase-adminsdk-fubgi-e15e1f43ed.json
  scope: https://www.googleapis.com/auth/cloud-platform